improve tripperware request id
gol4ng/httpware pull request #17
Opened 2019-09-25 16:22 UTC by instabledesign

2019-09-26 16:21 UTC, pimousse1099 submitted a review, later dismissed
maybe add some check on the tests ?

2019-09-26 16:21 UTC, rmasclef commented
rebase needed

2019-09-27 08:49 UTC, rmasclef commented
> rebase needed

done

2019-09-27 09:39 UTC, instabledesign commented on tripperware/request_id_test.go
> +	assert.NotEqual(t, req.Header.Get(request_id.HeaderName), "")
PRNG
`assert.Equal(t, "p1LGIehp1s", req.Header.Get(request_id.HeaderName))`

2019-09-27 11:52 UTC, pimousse1099 submitted a review, later dismissed

2019-09-27 12:57 UTC, qneyrat submitted a review, later dismissed

2019-09-27 13:03 UTC, pimousse1099 requested changes

2019-09-27 13:03 UTC, rmasclef commented on tripperware/request_id_test.go
> +	"github.com/stretchr/testify/assert"
Sort imports

2019-09-27 13:03 UTC, rmasclef commented on tripperware/request_id_test.go
> +	request_id.DefaultIdGenerator = request_id.NewRandomIdGenerator(
Nice

2019-09-27 13:09 UTC, merged