add doc on [middle|tripper]ware + simplify API
gol4ng/httpware pull request #2
Opened 2019-08-26 09:28 UTC by rmasclef

2019-08-26 17:42 UTC, instabledesign submitted a review, later dismissed

2019-08-26 17:42 UTC, instabledesign commented on middleware.go
> +// MiddlewareStack allows you to stack multiple middlewares in a specific order
i prefer group the receiver method with his type
same for round tripper

2019-08-26 17:42 UTC, instabledesign commented on middleware.go
> +// DecorateHandler will decorate a given http.Handler with the given middlewares created by MiddlewareStack()
`with the given middlewares collection`
same above

2019-08-26 17:42 UTC, instabledesign commented on tripperware.go
> +// RoundTrip implements RoundTripper interface
blank line

2019-08-26 17:42 UTC, instabledesign commented on tripperware.go
> +// DecorateRoundTripper will decorate a given http.RoundTripper with the given tripperwares created by TripperwareStack()
blank line

2019-08-26 17:42 UTC, instabledesign commented on tripperware.go
> +// DecorateRoundTripFunc will decorate a given RoundTripFunc with the given tripperwares created by MiddlewareStack()
blank line

2019-08-26 17:42 UTC, instabledesign commented on tripperware.go
> +// DecorateRoundTripFunc will decorate a given RoundTripFunc with the given tripperwares created by MiddlewareStack()
`with the given tripperwares collection`

2019-08-27 07:36 UTC, instabledesign requested changes

2019-08-27 07:36 UTC, instabledesign commented on middleware/metrics.go
> +			if !config.EnableMeasureRequestsInflight {
dont forget to revert condition to

2019-08-27 07:36 UTC, instabledesign commented on middleware/metrics.go
> +				if !config.EnableResponseMeasureSize {
dont forget to revert condition to

2019-08-27 07:36 UTC, instabledesign commented on tripperware/metrics_test.go
> +	monkey.Patch(time.Now, func() time.Time { return time.Unix(513216000, 0) })
create a variable with `time.Unix(513216000, 0)`

2019-08-27 07:36 UTC, instabledesign commented on tripperware_test.go
> +package httpware_test
dont forget to test tripperware/metrics to

2019-08-27 08:10 UTC, rmasclef commented on middleware/metrics.go
> +			if !config.EnableMeasureRequestsInflight {
oups, I forgot to commit that part 🤦‍♂

2019-08-27 18:03 UTC, instabledesign approved these changes

2019-08-27 18:03 UTC, merged