add rate limit tripperware
gol4ng/httpware pull request #33
Opened 2020-03-29 21:02 UTC by qneyrat

2020-03-29 21:27 UTC, instabledesign commented on tripperware/rate_limit.go
> +func RateLimit(rateLimiter rate_limit.RateLimiter, options ...RateLimitOption) httpware.Tripperware {
move the tripperware at first in this file

2020-03-29 21:27 UTC, instabledesign commented on tripperware/rate_limit.go
> +	args := &RateLimitOptions{
create a `func NewRateLimitOptions(options ...RateLimitOption)`
and create `func (o * RateLimitOptions)apply(options ...RateLimitOption)`

2020-03-30 15:22 UTC, instabledesign submitted a review, later dismissed
We really need to stabilize the test suite

2020-04-01 21:58 UTC, pimousse1099 submitted a review, later dismissed
👏 🎉

2020-09-01 16:20 UTC, instabledesign requested changes
dont forget to rebase on branch `v3` and
can you implement a TokenBucket base on request IP for example and have a concrete rate limiting example

2020-09-01 16:20 UTC, instabledesign commented on README.md
> +|**RateLimiter**| |X|
```suggestion
|**RateLimiter**|X|X|
```

2020-09-01 16:20 UTC, instabledesign commented on middleware/rate_limit.go
> +func RateLimit(rl rate_limit.RateLimiter, options ...RateLimitOption) httpware.Middleware {
can you name `limiter rate_limit.RateLimiter` instead of `rl`?

2020-09-01 16:20 UTC, instabledesign commented on middleware/rate_limit_test.go
> +	assert.Equal(t, http.StatusTooManyRequests, responseWriter.Code)
can you add the assertion on the response body plz with the returned error

2020-09-01 16:20 UTC, instabledesign commented on rate_limit/token_bucket.go
> +	mutex     sync.Mutex
~use RWMutex instead and use Lock / RLock~
prefer using the `atomic.AddInt64` package instead of mutex

2020-09-01 16:20 UTC, instabledesign commented on rate_limit/token_bucket.go
> +func NewTokenBucket(timeBucket time.Duration, callLimit int) *TokenBucket {
what do you think about usage of uint instead?
```suggestion
func NewTokenBucket(timeBucket time.Duration, callLimit uint) *TokenBucket {
```

2020-09-03 14:12 UTC, instabledesign approved these changes

2020-09-03 14:13 UTC, merged